
//post.rest file from the requests folder

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My first Blog",
  "author": "Andreea",
  "url": "https://blogName",
  "likes": 23,
  "user": "AndreeaC"
}
